name: backend
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.3

# Add regular dependencies here.
dependencies:
  postgresql2: ^1.5.1
  redis: ^4.0.0
  result_dart: ^1.1.1
  shelf: ^1.4.1
  shelf_modular: ^0.0.1
  uno: ^1.1.1
  # path: ^1.8.0

dev_dependencies:
  flutterando_analysis: ^0.0.2
  lints: ^3.0.0
  mocktail: ^1.0.3
  test: ^1.24.0
